# Generated by Django 5.2.7 on 2025-11-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_managers_user_deleted_at_user_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', help_text='Preferred language code', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='push_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='qc_alerts_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='reward_alerts_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='route_reminders_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
