# Generated by Django 5.2.7 on 2025-11-04 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_visits', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('successful_visits', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('skipped_visits', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('revenue_generated', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('other_metrics', models.JSONField(blank=True, help_text='Flexible storage for additional metrics', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'daily_summaries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'leave_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text="Reason for penalty (e.g., 'store skipped', 'route incomplete')")),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Financial penalty amount if applicable', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('penalty_type', models.CharField(choices=[('FINANCIAL', 'Financial'), ('WARNING', 'Warning')], default='WARNING', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('PAID', 'Paid'), ('DISPUTED', 'Disputed')], db_index=True, default='ISSUED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'penalties',
                'ordering': ['-issued_at'],
            },
        ),
    ]
