# Generated by Django 5.2.7 on 2025-11-04 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='counter',
            field=models.ForeignKey(limit_choices_to={'role': 'FIELD_AGENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='requester',
            field=models.ForeignKey(limit_choices_to={'role': 'FIELD_AGENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penalty',
            name='issued_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penalty',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties', to='core.route'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties', to='core.store'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'FIELD_AGENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='penalties_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dailysummary',
            index=models.Index(fields=['counter', 'date'], name='daily_summa_counter_5408b2_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysummary',
            index=models.Index(fields=['date'], name='daily_summa_date_4d8318_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailysummary',
            unique_together={('counter', 'date')},
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['requester', 'status'], name='leave_reque_request_2247fe_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status'], name='leave_reque_status_401183_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['start_date', 'end_date'], name='leave_reque_start_d_08703b_idx'),
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['user', 'status'], name='penalties_user_id_144dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['penalty_type'], name='penalties_penalty_5c2ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['issued_at'], name='penalties_issued__6418cf_idx'),
        ),
    ]
