# Generated by Django 5.2.7 on 2025-11-07 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysummary',
            name='counter',
            field=models.ForeignKey(limit_choices_to={'role': 'FIELD_AGENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='requester',
            field=models.ForeignKey(limit_choices_to={'role': 'FIELD_AGENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='issued_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'FIELD_AGENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='penalties_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
