# Generated by Django 5.2.7 on 2025-11-18 10:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_dailysummary_counter_and_more'),
        ('operations', '0006_image_quality_checked_at_image_quality_checked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='points_deducted',
            field=models.IntegerField(default=0, help_text='Points deducted for this penalty', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='penalty',
            name='store_visit',
            field=models.ForeignKey(blank=True, help_text='Store visit that resulted in this penalty', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties', to='operations.storevisit'),
        ),
    ]
