# Generated by Django 5.2.7 on 2025-11-04 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'FIELD_AGENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='counter_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='route',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Manager who approved this route', limit_choices_to={'role': 'MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='route',
            name='user',
            field=models.ForeignKey(help_text='Field agent assigned to this route', limit_choices_to={'role': 'FIELD_AGENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routestore',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stores', to='core.route'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['status'], name='stores_status_ecb921_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['latitude', 'longitude'], name='stores_latitud_c3b239_idx'),
        ),
        migrations.AddField(
            model_name='routestore',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stores', to='core.store'),
        ),
        migrations.AddIndex(
            model_name='counter',
            index=models.Index(fields=['employee_id'], name='counters_employe_17ce0f_idx'),
        ),
        migrations.AddIndex(
            model_name='counter',
            index=models.Index(fields=['status'], name='counters_status_919d76_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['user', 'date'], name='routes_user_id_212b84_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['status'], name='routes_status_4a5f34_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['date'], name='routes_date_e961bb_idx'),
        ),
        migrations.AddIndex(
            model_name='routestore',
            index=models.Index(fields=['route', 'order'], name='route_store_route_i_7038d0_idx'),
        ),
        migrations.AddIndex(
            model_name='routestore',
            index=models.Index(fields=['status'], name='route_store_status_75db0b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routestore',
            unique_together={('route', 'store')},
        ),
    ]
