# Generated by Django 5.2.7 on 2025-11-05 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(help_text='Image file', upload_to='file_manager/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('DOCUMENT', 'Document'), ('VIDEO', 'Video'), ('OTHER', 'Other')], db_index=True, default='IMAGE', help_text='Type of file', max_length=20)),
                ('image_category', models.CharField(blank=True, choices=[('PRODUCT', 'Product'), ('STOREFRONT', 'Storefront'), ('SIGNATURE', 'Signature'), ('ID_PROOF', 'ID Proof'), ('INVOICE', 'Invoice'), ('RECEIPT', 'Receipt'), ('OTHER', 'Other')], db_index=True, help_text='Category of image (if file_type is IMAGE)', max_length=20, null=True)),
                ('description', models.TextField(blank=True, help_text='Description or notes about the file', null=True)),
                ('file_name', models.CharField(blank=True, help_text='Original file name', max_length=255, null=True)),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the file is active/visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(blank=True, help_text='Route associated with this file (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.route')),
                ('user', models.ForeignKey(help_text='User who uploaded the file', on_delete=django.db.models.deletion.CASCADE, related_name='managed_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_manager',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='file_manage_user_id_17aa0c_idx'), models.Index(fields=['route', 'created_at'], name='file_manage_route_i_70bc25_idx'), models.Index(fields=['file_type'], name='file_manage_file_ty_08a176_idx'), models.Index(fields=['image_category'], name='file_manage_image_c_e17bb8_idx'), models.Index(fields=['is_active'], name='file_manage_is_acti_58e481_idx')],
            },
        ),
    ]
