# Generated by Django 5.2.7 on 2025-11-07 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_filemanager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'FIELD_AGENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='counter_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='route',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Manager who approved this route', limit_choices_to={'role': 'MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='route',
            name='user',
            field=models.ForeignKey(help_text='Field agent assigned to this route', limit_choices_to={'role': 'FIELD_AGENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_routes', to=settings.AUTH_USER_MODEL),
        ),
    ]
