# Generated by Django 5.2.7 on 2025-11-12 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_counter_user_alter_route_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='filemanager',
            name='file_manage_image_c_e17bb8_idx',
        ),
        migrations.RemoveField(
            model_name='filemanager',
            name='image_category',
        ),
        migrations.AddField(
            model_name='filemanager',
            name='bucket',
            field=models.CharField(blank=True, default='', help_text='Object storage bucket where the file is stored', max_length=255),
        ),
        migrations.AddField(
            model_name='filemanager',
            name='checksum',
            field=models.CharField(blank=True, help_text='Checksum (MD5) of the stored file for integrity validation', max_length=128),
        ),
        migrations.AddField(
            model_name='filemanager',
            name='content_type',
            field=models.CharField(blank=True, help_text='MIME type detected for this file', max_length=127),
        ),
        migrations.AddField(
            model_name='filemanager',
            name='object_key',
            field=models.CharField(blank=True, help_text='Full object key/path within the storage bucket', max_length=512, unique=True),
        ),
        migrations.AddField(
            model_name='filemanager',
            name='purpose',
            field=models.CharField(choices=[('GENERAL', 'General'), ('PROFILE_IMAGE', 'Profile Image'), ('ROUTE_ATTACHMENT', 'Route Attachment'), ('REPORT_ATTACHMENT', 'Report Attachment'), ('USER_DOCUMENT', 'User Document')], db_index=True, default='GENERAL', help_text='Business purpose or usage context for this file', max_length=50),
        ),
        migrations.AlterField(
            model_name='filemanager',
            name='file',
            field=models.FileField(help_text='Uploaded file stored in object storage', upload_to='file_manager/%Y/%m/%d/'),
        ),
        migrations.AddIndex(
            model_name='filemanager',
            index=models.Index(fields=['purpose'], name='file_manage_purpose_8c9986_idx'),
        ),
        migrations.AddIndex(
            model_name='filemanager',
            index=models.Index(fields=['bucket'], name='file_manage_bucket_26b1e0_idx'),
        ),
    ]
