# Generated by Django 5.2.7 on 2025-11-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_filemanager_file_manage_image_c_e17bb8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemanager',
            name='object_key',
            field=models.CharField(blank=True, help_text='Full object key/path within the storage bucket', max_length=512, null=True, unique=True),
        ),
    ]
