# Generated by Django 5.2.7 on 2025-11-14 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_filemanager_object_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="District name (e.g., 'Al Naseem', 'Al Rawdah')", max_length=200, unique=True)),
                ('code', models.CharField(blank=True, db_index=True, help_text='Optional district code/abbreviation', max_length=50, null=True, unique=True)),
                ('priority', models.CharField(choices=[('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority')], db_index=True, default='MEDIUM', help_text='Priority level for district operations', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional information about the district', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'districts',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status'], name='districts_status_d507b8_idx'), models.Index(fields=['priority'], name='districts_priorit_30e206_idx'), models.Index(fields=['name'], name='districts_name_961bdc_idx')],
            },
        ),
        migrations.AddField(
            model_name='route',
            name='district',
            field=models.ForeignKey(blank=True, help_text='District this route is specific to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='core.district'),
        ),
        migrations.AddField(
            model_name='store',
            name='district',
            field=models.ForeignKey(blank=True, help_text='District this store belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='core.district'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['district'], name='routes_distric_4b4289_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['district'], name='stores_distric_af1e37_idx'),
        ),
    ]
