# Generated by Django 5.2.7 on 2025-11-14 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_district_route_district_store_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='district',
            field=models.ForeignKey(blank=True, help_text='District this route is specific to (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='core.district'),
        ),
        migrations.AlterField(
            model_name='store',
            name='district',
            field=models.ForeignKey(blank=True, help_text='District this store belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='core.district'),
        ),
    ]
