# Generated by Django 5.2.7 on 2025-11-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_change_district_cascade'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='counter',
            name='counters_status_919d76_idx',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='status',
        ),
        migrations.AlterField(
            model_name='filemanager',
            name='bucket',
            field=models.CharField(blank=True, help_text='Object storage bucket where the file is stored (auto-populated)', max_length=255),
        ),
        migrations.AlterField(
            model_name='filemanager',
            name='object_key',
            field=models.CharField(blank=True, help_text='Full object key/path within the storage bucket (auto-populated)', max_length=512, null=True),
        ),
    ]
