# Generated by Django 5.2.7 on 2025-11-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_counter_status_use_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemanager',
            name='purpose',
            field=models.CharField(choices=[('GENERAL', 'General'), ('PROFILE_IMAGE', 'Profile Image'), ('ROUTE_ATTACHMENT', 'Route Attachment'), ('REPORT_ATTACHMENT', 'Report Attachment'), ('USER_DOCUMENT', 'User Document'), ('PERMISSION_FORM_SIGNATURE', 'Permission Form Signature')], db_index=True, default='GENERAL', help_text='Business purpose or usage context for this file', max_length=50),
        ),
    ]
