# Generated by Django 5.2.7 on 2025-11-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_filemanager_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority')], db_index=True, default='MEDIUM', help_text='Store priority level (affects penalty calculation for missed visits)', max_length=20),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['priority'], name='stores_priorit_76589d_idx'),
        ),
    ]
