# Generated by Django 5.2.7 on 2025-11-04 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financetransaction',
            name='recorded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reward',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rewards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreward',
            name='awarded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['MANAGER', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreward',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rewards', to='finance.reward'),
        ),
        migrations.AddField(
            model_name='userreward',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'FIELD_AGENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='rewards_awarded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='processed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='reward',
            field=models.ForeignKey(blank=True, help_text='Specific reward if linked', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='finance.userreward'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'FIELD_AGENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='financetransaction',
            index=models.Index(fields=['transaction_type', 'date'], name='finance_tra_transac_13e0ef_idx'),
        ),
        migrations.AddIndex(
            model_name='financetransaction',
            index=models.Index(fields=['related_user', 'date'], name='finance_tra_related_727684_idx'),
        ),
        migrations.AddIndex(
            model_name='financetransaction',
            index=models.Index(fields=['date'], name='finance_tra_date_444869_idx'),
        ),
        migrations.AddIndex(
            model_name='reward',
            index=models.Index(fields=['is_active'], name='rewards_is_acti_0dfe38_idx'),
        ),
        migrations.AddIndex(
            model_name='userreward',
            index=models.Index(fields=['user', 'status'], name='user_reward_user_id_9633e9_idx'),
        ),
        migrations.AddIndex(
            model_name='userreward',
            index=models.Index(fields=['status'], name='user_reward_status_8b1fe1_idx'),
        ),
        migrations.AddIndex(
            model_name='userreward',
            index=models.Index(fields=['earned_at'], name='user_reward_earned__b18c4b_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['user', 'status'], name='withdrawals_user_id_38a9fa_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['status'], name='withdrawals_status_ddef8f_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['request_date'], name='withdrawals_request_083d45_idx'),
        ),
    ]
