# Generated by Django 5.2.7 on 2025-11-07 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rewards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userreward',
            name='awarded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['MANAGER', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userreward',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'FIELD_AGENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='rewards_awarded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='processed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'FIELD_AGENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL),
        ),
    ]
