# Generated by Django 5.2.7 on 2025-11-18 10:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_store_priority_store_stores_priorit_76589d_idx'),
        ('finance', '0003_alter_reward_created_by_alter_userreward_awarded_by_and_more'),
        ('operations', '0006_image_quality_checked_at_image_quality_checked_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userreward',
            name='activity_type',
            field=models.CharField(blank=True, help_text="Activity that earned this reward (e.g., 'Perfect Visit', 'Visit Completion')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userreward',
            name='points_earned',
            field=models.IntegerField(default=0, help_text='Points earned from this activity', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='userreward',
            name='store_visit',
            field=models.ForeignKey(blank=True, help_text='Store visit that earned this reward', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards_earned', to='operations.storevisit'),
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('EARNED', 'Earned'), ('DEDUCTED', 'Deducted'), ('REDEEMED', 'Redeemed')], db_index=True, max_length=20)),
                ('activity_type', models.CharField(choices=[('VISIT_COMPLETION', 'Visit Completion'), ('PERFECT_VISIT', 'Perfect Visit'), ('IMAGE_QUALITY_BONUS', 'Image Quality Bonus'), ('IMAGE_REJECTION_PENALTY', 'Image Rejection Penalty'), ('MISSED_VISIT_PENALTY', 'Missed Visit Penalty'), ('HIGH_PRIORITY_MISSED', 'High Priority Store Missed'), ('REWARD_REDEMPTION', 'Reward Redemption')], db_index=True, help_text='Type of activity that generated this transaction', max_length=50)),
                ('points', models.IntegerField(help_text='Points amount (positive for earned, negative for deducted)')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_transactions', to='core.route')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_transactions', to='core.store')),
                ('store_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_transactions', to='operations.storevisit')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'FIELD_AGENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'points_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='points_tran_user_id_86aa8f_idx'), models.Index(fields=['transaction_type', 'created_at'], name='points_tran_transac_ff715d_idx'), models.Index(fields=['activity_type', 'created_at'], name='points_tran_activit_508091_idx'), models.Index(fields=['store_visit'], name='points_tran_store_v_129d5c_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0, help_text='Current total points balance', validators=[django.core.validators.MinValueValidator(0)])),
                ('available_points', models.IntegerField(default=0, help_text='Points available for redemption', validators=[django.core.validators.MinValueValidator(0)])),
                ('lifetime_points', models.IntegerField(default=0, help_text='Total points earned lifetime', validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'FIELD_AGENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='points_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_points',
                'ordering': ['-total_points'],
                'indexes': [models.Index(fields=['total_points'], name='user_points_total_p_28c9e8_idx'), models.Index(fields=['user'], name='user_points_user_id_8b3440_idx')],
            },
        ),
    ]
