# Generated by Django 5.2.7 on 2025-11-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('schema', models.JSONField(blank=True, default=dict, help_text='Dataset schema definition', null=True)),
                ('access_roles', models.JSONField(blank=True, default=list, help_text='Roles that can access this dataset', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'datasets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadableFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(help_text='File available for download', upload_to='downloadable_files/')),
                ('file_type', models.CharField(help_text='File type/category', max_length=50)),
                ('size', models.IntegerField(help_text='File size in bytes')),
                ('access_roles', models.JSONField(blank=True, default=list, help_text='Roles that can download this file', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'downloadable_files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'download_history',
                'ordering': ['-download_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('category', models.CharField(blank=True, help_text='Category for organizing FAQs', max_length=100, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'faqs',
                'ordering': ['category', 'question'],
            },
        ),
        migrations.CreateModel(
            name='InsightPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('configuration', models.JSONField(default=dict, help_text='Display settings and configuration')),
                ('data_source', models.CharField(help_text='Source of data for this panel', max_length=200)),
                ('access_roles', models.JSONField(blank=True, default=list, help_text="Roles that can view this panel, e.g., ['ADMIN', 'MANAGER']", null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'insight_panels',
                'ordering': ['-created_at'],
            },
        ),
    ]
