# Generated by Django 5.2.7 on 2025-11-04 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_datasets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='downloadablefile',
            name='uploaded_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['MANAGER', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='downloadhistory',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_history', to='dashboard.downloadablefile'),
        ),
        migrations.AddField(
            model_name='downloadhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['category', 'is_active'], name='faqs_categor_839aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['is_active'], name='faqs_is_acti_3459f3_idx'),
        ),
        migrations.AddField(
            model_name='insightpanel',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_insight_panels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['owner'], name='datasets_owner_i_ba6aea_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadablefile',
            index=models.Index(fields=['file_type'], name='downloadabl_file_ty_fc5f55_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadablefile',
            index=models.Index(fields=['created_at'], name='downloadabl_created_317c2a_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadhistory',
            index=models.Index(fields=['user', 'download_timestamp'], name='download_hi_user_id_56bde1_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadhistory',
            index=models.Index(fields=['download_timestamp'], name='download_hi_downloa_52e753_idx'),
        ),
        migrations.AddIndex(
            model_name='insightpanel',
            index=models.Index(fields=['is_active'], name='insight_pan_is_acti_743a88_idx'),
        ),
    ]
