# Generated by Django 5.2.7 on 2025-11-07 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadablefile',
            name='uploaded_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['MANAGER', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='insightpanel',
            name='access_roles',
            field=models.JSONField(blank=True, default=list, help_text="Roles that can view this panel, e.g., ['ADMIN', 'MANAGER']", null=True),
        ),
        migrations.AlterField(
            model_name='insightpanel',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_insight_panels', to=settings.AUTH_USER_MODEL),
        ),
    ]
