# Generated by Django 5.2.7 on 2025-11-04 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_leaves_per_year', models.IntegerField(default=20, help_text='Maximum number of leaves allowed per year')),
                ('leave_types', models.JSONField(blank=True, default=dict, help_text="Leave types as JSON, e.g., {'sick': 10, 'casual': 5}", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'leave_settings',
            },
        ),
        migrations.CreateModel(
            name='ProfileSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_preference', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', max_length=20)),
                ('notification_settings', models.JSONField(blank=True, default=dict, help_text='Notification preferences as JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'profile_settings',
            },
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_entity_type', models.CharField(db_index=True, help_text="e.g., 'STORE_VISIT', 'IMAGE'", max_length=50)),
                ('related_entity_id', models.IntegerField()),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='quality_checks/')),
                ('json_data', models.JSONField(blank=True, help_text='Structured quality check results', null=True)),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('PENDING', 'Pending')], db_index=True, default='PENDING', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'quality_checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(db_index=True, max_length=100, unique=True)),
                ('default_filters', models.JSONField(blank=True, default=dict, help_text='Default filters for this report type', null=True)),
                ('access_roles', models.JSONField(blank=True, default=list, help_text="Roles that can access this report, e.g., ['ADMIN', 'MANAGER']", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'report_settings',
                'ordering': ['report_type'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed'), ('PENDING', 'Pending')], db_index=True, default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'support_tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField()),
                ('data_type', models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('BOOLEAN', 'Boolean'), ('JSON', 'JSON')], default='STRING', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_settings',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='CounterSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(max_length=100)),
                ('setting_value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_settings', to='core.counter')),
            ],
            options={
                'db_table': 'counter_settings',
                'ordering': ['counter', 'setting_key'],
            },
        ),
    ]
