# Generated by Django 5.2.7 on 2025-11-04 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesetting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='checked_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['MANAGER', 'ADMIN']}, on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['MANAGER', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='updated_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='countersetting',
            unique_together={('counter', 'setting_key')},
        ),
        migrations.AddIndex(
            model_name='qualitycheck',
            index=models.Index(fields=['related_entity_type', 'related_entity_id'], name='quality_che_related_96c4d0_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitycheck',
            index=models.Index(fields=['status'], name='quality_che_status_4d3d87_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitycheck',
            index=models.Index(fields=['created_at'], name='quality_che_created_ad4933_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['user', 'status'], name='support_tic_user_id_057736_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'priority'], name='support_tic_status_c8e2c5_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['created_at'], name='support_tic_created_026818_idx'),
        ),
    ]
