# Generated by Django 5.2.7 on 2025-11-07 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitycheck',
            name='checked_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['MANAGER', 'ADMIN']}, on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportsetting',
            name='access_roles',
            field=models.JSONField(blank=True, default=list, help_text="Roles that can access this report, e.g., ['ADMIN', 'MANAGER']", null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['MANAGER', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='updated_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
