# Generated by Django 5.2.7 on 2025-11-13 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_filemanager_object_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('SICK', 'Sick Leave'), ('CASUAL', 'Causal Leave')], db_index=True, default='SICK', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, help_text='Manager or admin who reviewed the request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, help_text='Optional supporting document stored in File Manager.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests', to='core.filemanager')),
                ('requested_by', models.ForeignKey(help_text='User who submitted the leave request.', on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leaves_leave_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requested_by', 'start_date', 'end_date'], name='leaves_leav_request_fbefd2_idx'), models.Index(fields=['status'], name='leaves_leav_status_c5d4e2_idx')],
            },
        ),
    ]
