# Generated by Django 5.2.7 on 2025-11-04 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='break',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'FIELD_AGENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkin',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'FIELD_AGENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captured_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storevisit',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_store_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storevisit',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_visits', to='core.route'),
        ),
        migrations.AddField(
            model_name='storevisit',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.store'),
        ),
        migrations.AddField(
            model_name='storevisit',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'FIELD_AGENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='store_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissionform',
            name='store_visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission_form', to='operations.storevisit'),
        ),
        migrations.AddField(
            model_name='image',
            name='store_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='operations.storevisit'),
        ),
        migrations.AddIndex(
            model_name='break',
            index=models.Index(fields=['user', 'route'], name='breaks_user_id_d61d5c_idx'),
        ),
        migrations.AddIndex(
            model_name='break',
            index=models.Index(fields=['start_time'], name='breaks_start_t_f8f24a_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['user', 'timestamp'], name='check_ins_user_id_2daaea_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['timestamp'], name='check_ins_timesta_a7f8ec_idx'),
        ),
        migrations.AddIndex(
            model_name='storevisit',
            index=models.Index(fields=['user', 'route'], name='store_visit_user_id_d4e26f_idx'),
        ),
        migrations.AddIndex(
            model_name='storevisit',
            index=models.Index(fields=['store', 'status'], name='store_visit_store_i_8c6256_idx'),
        ),
        migrations.AddIndex(
            model_name='storevisit',
            index=models.Index(fields=['status'], name='store_visit_status_3c9471_idx'),
        ),
        migrations.AddIndex(
            model_name='storevisit',
            index=models.Index(fields=['ai_ml_check_status'], name='store_visit_ai_ml_c_c8b751_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['store_visit', 'captured_at'], name='images_store_v_1f2c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['image_type'], name='images_image_t_3c70d3_idx'),
        ),
    ]
