# Generated by Django 5.2.7 on 2025-11-13 12:22

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_filemanager_object_key'),
        ('operations', '0003_alter_break_user_alter_checkin_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='break',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Work session this break belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='break_entries', to='operations.checkin'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='check_out_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude captured at checkout.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='checkin',
            name='check_out_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude captured at checkout.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='checkin',
            name='check_out_time',
            field=models.DateTimeField(blank=True, help_text='Timestamp recorded when the agent checked out.', null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='current_break_start',
            field=models.DateTimeField(blank=True, help_text='Start timestamp for an ongoing break.', null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='shift_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, help_text='Calendar date associated with this work session.'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ON_BREAK', 'On Break'), ('COMPLETED', 'Completed')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='checkin',
            name='total_break_duration',
            field=models.DurationField(default=datetime.timedelta, help_text='Cumulative duration of all breaks taken during the session.'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='break',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='core.route'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Check-in timestamp when the work session started.'),
        ),
        migrations.AddIndex(
            model_name='break',
            index=models.Index(fields=['session', 'start_time'], name='breaks_session_b0e246_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['user', 'shift_date', 'status'], name='check_ins_user_id_7a4fe8_idx'),
        ),
        migrations.AddConstraint(
            model_name='checkin',
            constraint=models.UniqueConstraint(fields=('user', 'shift_date'), name='unique_shift_per_user_per_day'),
        ),
    ]
