# Generated by Django 5.2.7 on 2025-11-17 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_filemanager_purpose'),
        ('operations', '0004_break_session_checkin_check_out_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('STORE_CLOSED_PERMANENTLY', 'Store closed permanently'), ('ACCESS_DENIED', 'Access denied'), ('WRONG_LOCATION_DUPLICATE', 'Wrong location or duplicate'), ('INVENTORY_ISSUE', 'Inventory issue'), ('OTHER', 'Other')], db_index=True, help_text='Reason for flagging the store', max_length=50)),
                ('additional_details', models.TextField(blank=True, help_text='Additional details about why the store was flagged', null=True)),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(db_index=True, default=False, help_text='Whether the flag has been resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'flagged_stores',
                'ordering': ['-flagged_at'],
            },
        ),
        migrations.AddField(
            model_name='permissionform',
            name='is_flagged',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this store visit was flagged'),
        ),
        migrations.AddField(
            model_name='permissionform',
            name='permission_granted_confirmed',
            field=models.BooleanField(default=False, help_text='Counter confirms permission has been granted'),
        ),
        migrations.AddField(
            model_name='permissionform',
            name='permission_received',
            field=models.BooleanField(blank=True, help_text='Has permission been received to start counting?', null=True),
        ),
        migrations.AddField(
            model_name='permissionform',
            name='ready_to_begin_collection',
            field=models.BooleanField(default=False, help_text='Counter is ready to begin data collection'),
        ),
        migrations.AddField(
            model_name='permissionform',
            name='representative_contact',
            field=models.CharField(blank=True, help_text='Store representative contact number (optional)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='permissionform',
            name='representative_designation',
            field=models.CharField(blank=True, help_text='Store representative designation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='permissionform',
            name='representative_details_verified',
            field=models.BooleanField(default=False, help_text='Counter has verified representative details'),
        ),
        migrations.AddField(
            model_name='permissionform',
            name='representative_name',
            field=models.CharField(blank=True, help_text='Store representative name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='permissionform',
            name='signature',
            field=models.ForeignKey(blank=True, help_text='Signature image (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_form_signatures', to='core.filemanager'),
        ),
        migrations.AddField(
            model_name='permissionform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='permissionform',
            name='form_data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional flexible form data storage'),
        ),
        migrations.AlterField(
            model_name='storevisit',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('FLAGGED', 'Flagged')], db_index=True, default='IN_PROGRESS', max_length=20),
        ),
        migrations.AddIndex(
            model_name='permissionform',
            index=models.Index(fields=['is_flagged'], name='permission__is_flag_2aeaab_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionform',
            index=models.Index(fields=['submitted_at'], name='permission__submitt_99c363_idx'),
        ),
        migrations.AddField(
            model_name='flaggedstore',
            name='flagged_by',
            field=models.ForeignKey(help_text='User who flagged the store', on_delete=django.db.models.deletion.CASCADE, related_name='flagged_stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flaggedstore',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='Manager/admin who resolved the flag', limit_choices_to={'role__in': ['MANAGER', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flaggedstore',
            name='store_visit',
            field=models.OneToOneField(help_text='Store visit that was flagged', on_delete=django.db.models.deletion.CASCADE, related_name='flagged_store', to='operations.storevisit'),
        ),
        migrations.AddIndex(
            model_name='flaggedstore',
            index=models.Index(fields=['reason'], name='flagged_sto_reason_bade64_idx'),
        ),
        migrations.AddIndex(
            model_name='flaggedstore',
            index=models.Index(fields=['is_resolved'], name='flagged_sto_is_reso_80effe_idx'),
        ),
        migrations.AddIndex(
            model_name='flaggedstore',
            index=models.Index(fields=['flagged_at'], name='flagged_sto_flagged_835ba4_idx'),
        ),
    ]
