# Generated by Django 5.2.7 on 2025-11-18 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_flaggedstore_permissionform_is_flagged_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='quality_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='quality_checked_by',
            field=models.ForeignKey(blank=True, help_text='User who approved/rejected this image', limit_choices_to={'role__in': ['MANAGER', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checked_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='quality_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', help_text='Image quality approval status', max_length=20),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['quality_status'], name='images_quality_80d440_idx'),
        ),
    ]
